// Stamp /gree content with a hash so devices refetch it only when it changes.
// Run after editing src/data/gree/words.json or questions.json.
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';

const h = createHash('sha256');
for (const f of ['words.json', 'questions.json']) h.update(readFileSync(new URL(`../src/data/gree/${f}`, import.meta.url)));
const v = h.digest('hex').slice(0, 12);
writeFileSync(
  new URL('../src/data/gree/version.ts', import.meta.url),
  `// Generated by scripts/gree-version.mjs. Do not edit.\nexport const CONTENT_VERSION = '${v}';\n`,
);
console.log(v);
