#!/usr/bin/env node
/**
 * Turn scripts/learning-curriculum.mjs into SQL, and optionally apply it.
 *
 *   node scripts/learning-seed.mjs                 # print the SQL
 *   node scripts/learning-seed.mjs --apply         # apply to the remote D1
 *   node scripts/learning-seed.mjs --apply --local # apply to the local dev D1
 *
 * Every id is derived from the content rather than random, and every insert is
 * an upsert, so this is safe to re-run after editing the curriculum. That
 * matters more than it looks: the problem rows are the join target for every
 * attempt ever recorded, and a reseed that allocated new ids would silently
 * orphan the entire history.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  BREAKS, COMPUTER, SHEETS, START_DATE, TOPICS, buragoSessions,
} from './learning-curriculum.mjs';

const NOW = new Date().toISOString();
const MATH_COURSE = 'course:burago-y1';
const COMP_COURSE = 'course:computer';

const q = (v) => (v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const out = [];
const add = (sql) => out.push(sql);

// ─────────────────────────────────────────────────────────────── courses

add(`-- generated by scripts/learning-seed.mjs on ${NOW}. Do not edit by hand.`);
add('PRAGMA foreign_keys = ON;');

for (const [id, name, strand, source] of [
  [MATH_COURSE, 'Mathematical Circle Diaries, Year 1', 'math', 'Anna Burago, MSRI'],
  [COMP_COURSE, 'Computer track', 'computer', null],
]) {
  add(
    `INSERT INTO course (id, name, strand, source, active, created_at) VALUES (${q(id)}, ${q(name)}, ${q(strand)}, ${q(source)}, 1, ${q(NOW)})
     ON CONFLICT(id) DO UPDATE SET name = excluded.name, source = excluded.source;`,
  );
}

// ──────────────────────────────────────────────────────────────── topics

TOPICS.forEach(([id, name, strand], i) => {
  add(
    `INSERT INTO topic (id, name, strand, sort) VALUES (${q('topic:' + id)}, ${q(name)}, ${q(strand)}, ${i})
     ON CONFLICT(id) DO UPDATE SET name = excluded.name, sort = excluded.sort;`,
  );
});

// ──────────────────────────────────────────────────── maths sessions

const sessions = buragoSessions();

for (const s of sessions) {
  const id = `sess:burago-y1:${s.seq}`;
  add(
    `INSERT INTO session (id, course_id, seq, title, kind, sheet_slug, created_at)
     VALUES (${q(id)}, ${q(MATH_COURSE)}, ${s.seq}, ${q(s.title)}, ${q(s.kind)}, ${q(s.sheet_slug)}, ${q(NOW)})
     ON CONFLICT(id) DO UPDATE SET title = excluded.title, kind = excluded.kind, sheet_slug = excluded.sheet_slug;`,
  );

  const sheet = SHEETS[s.seq];
  if (!sheet) continue;

  const refs = new Set(sheet.problems.map(([ref]) => ref));

  sheet.problems.forEach(([ref, label, kind, answer, topics], i) => {
    const pid = `prob:burago-y1:${s.seq}:${ref}`;
    // A ref like '1b' or '8b' is a sub-part of '1' / '8'. Both curricula are
    // graded per sub-part, so the parts are rows, not a note on the parent.
    // Where the sheet has no unlettered parent — Sheet 1 numbers its marble
    // problem 3a and 3b with no bare '3' — the first lettered part stands in
    // as the parent rather than leaving a dangling reference.
    let parentRef = null;
    if (kind === 'part') {
      const stem = ref.replace(/[a-z]$/, '');
      parentRef = refs.has(stem) ? stem : refs.has(stem + 'a') ? stem + 'a' : null;
    }
    const parent = parentRef ? `prob:burago-y1:${s.seq}:${parentRef}` : null;

    add(
      `INSERT INTO problem (id, session_id, parent_id, ref, label, kind, position, created_at)
       VALUES (${q(pid)}, ${q(id)}, ${q(parent)}, ${q(ref)}, ${q(label)}, ${q(kind)}, ${i}, ${q(NOW)})
       ON CONFLICT(id) DO UPDATE SET label = excluded.label, kind = excluded.kind,
                                     parent_id = excluded.parent_id, position = excluded.position;`,
    );
    add(
      `INSERT INTO problem_answer (problem_id, answer) VALUES (${q(pid)}, ${q(answer)})
       ON CONFLICT(problem_id) DO UPDATE SET answer = excluded.answer;`,
    );
    for (const t of topics) {
      add(`INSERT OR IGNORE INTO problem_topic (problem_id, topic_id) VALUES (${q(pid)}, ${q('topic:' + t)});`);
    }
  });
}

// ─────────────────────────────────────────────────── computer sessions

COMPUTER.forEach(([ref, title, tasks], i) => {
  const id = `sess:computer:${ref}`;
  add(
    `INSERT INTO session (id, course_id, seq, title, kind, created_at)
     VALUES (${q(id)}, ${q(COMP_COURSE)}, ${i + 1}, ${q(title)}, 'computer', ${q(NOW)})
     ON CONFLICT(id) DO UPDATE SET title = excluded.title;`,
  );
  tasks.forEach(([tref, ttitle, kind, evidence], j) => {
    add(
      `INSERT INTO task (id, session_id, ref, title, kind, evidence_kind, position)
       VALUES (${q(`task:${ref}:${tref}`)}, ${q(id)}, ${q(tref)}, ${q(ttitle)}, ${q(kind)}, ${q(evidence)}, ${j})
       ON CONFLICT(id) DO UPDATE SET title = excluded.title, kind = excluded.kind,
                                     evidence_kind = excluded.evidence_kind, position = excluded.position;`,
    );
  });
});

// ────────────────────────────────────────────────────────────── breaks

for (const [start, end, reason] of BREAKS) {
  add(
    `INSERT INTO break_period (id, start_on, end_on, reason)
     VALUES (${q(`break:${start}`)}, ${q(start)}, ${q(end)}, ${q(reason)})
     ON CONFLICT(id) DO UPDATE SET end_on = excluded.end_on, reason = excluded.reason;`,
  );
}

// ──────────────────────────────────────────────────────────── calendar

/**
 * Saturdays, skipping declared breaks.
 *
 * Deliberately NOT "week N". An Indian school year yields about 34 usable
 * Saturdays, not 52, and every plan that counts weeks ends up reporting a
 * failure every exam season.
 */
function saturdaysFrom(startIso, count) {
  const dates = [];
  const d = new Date(startIso + 'T00:00:00Z');
  while (dates.length < count) {
    const iso = d.toISOString().slice(0, 10);
    const inBreak = BREAKS.some(([a, b]) => a <= iso && iso <= b);
    if (!inBreak) dates.push(iso);
    d.setUTCDate(d.getUTCDate() + 7);
  }
  return dates;
}

// Sheet 1 was taught on the evening of 31 August 2026. It is seeded as a
// closed but ungraded evening so that it lands at the top of the grade queue
// with nothing invented: no outcomes are written here, only the fact that it
// happened. Delete the two statements below if that date is wrong.
add(
  `INSERT INTO planned (id, session_id, on_date, state) VALUES ('plan:burago-y1:1', 'sess:burago-y1:1', '2026-08-31', 'done')
   ON CONFLICT(id) DO UPDATE SET on_date = excluded.on_date, state = excluded.state;`,
);
add(
  `INSERT INTO entry (id, session_id, on_date, closed_at, created_at)
   VALUES ('entry:seed:s1', 'sess:burago-y1:1', '2026-08-31', ${q(NOW)}, ${q(NOW)})
   ON CONFLICT(id) DO NOTHING;`,
);

const upcoming = sessions.filter((s) => s.seq >= 2);
saturdaysFrom(START_DATE, upcoming.length).forEach((date, i) => {
  const s = upcoming[i];
  add(
    `INSERT INTO planned (id, session_id, on_date, state)
     VALUES (${q(`plan:burago-y1:${s.seq}`)}, ${q(`sess:burago-y1:${s.seq}`)}, ${q(date)}, 'planned')
     ON CONFLICT(id) DO UPDATE SET on_date = excluded.on_date;`,
  );
});

// ─────────────────────────────────────────────────────────────── output

const sql = out.join('\n') + '\n';
const apply = process.argv.includes('--apply');

if (!apply) {
  process.stdout.write(sql);
  process.exit(0);
}

const dir = mkdtempSync(join(tmpdir(), 'learning-seed-'));
const file = join(dir, 'seed.sql');
writeFileSync(file, sql);

const args = ['wrangler', 'd1', 'execute', 'learning', process.argv.includes('--local') ? '--local' : '--remote', '--file', file, '-y'];
console.error(`applying ${out.length} statements…`);
execFileSync('npx', args, { stdio: 'inherit' });
